version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VIRTUAL_HOST=fckfsh.ru
      - LETSENCRYPT_HOST=fckfsh.ru
      - LETSENCRYPT_EMAIL=your-email@example.com
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - web

networks:
  web:
    external: true 