"""Добавлены tg_id и photo_url

Revision ID: 5346621406c5
Revises: 
Create Date: 2025-02-04 14:42:06.896118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5346621406c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('photo_url', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###
